# Generated by Django 3.2.25 on 2025-03-23 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.TextField(max_length=2000)),
                ('objective', models.TextField(max_length=1000)),
                ('skills', models.CharField(max_length=500)),
                ('experience', models.TextField(max_length=1000)),
                ('education', models.TextField(max_length=1000)),
                ('certifications', models.TextField(blank=True, max_length=1000)),
                ('projects', models.TextField(blank=True, max_length=1000)),
                ('achievements', models.TextField(blank=True, max_length=1000)),
                ('languages', models.CharField(blank=True, max_length=100)),
                ('hobbies', models.CharField(blank=True, max_length=300)),
                ('portfolio_link', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.student')),
            ],
        ),
    ]
