# Generated by Django 3.2.25 on 2025-03-23 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(max_length=1500)),
                ('is_correct', models.BooleanField(default=False)),
                ('time_taken', models.CharField(max_length=1500)),
                ('result', models.CharField(max_length=1500)),
                ('attempt', models.CharField(max_length=1500)),
                ('MOCK_TEST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.mock_test')),
                ('QUESTION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.question')),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.student')),
            ],
        ),
    ]
